Group settings
MonkeyCodingTeam/huzin-service pull request #13
Opened 2023-10-23 16:38 UTC by KM-DEV01

2023-10-23 17:32 UTC, grizzlygarillaz requested changes

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/entities/group/ui/GroupInfo.tsx
> +            <div className={css.groupInfo__imageContainer}>
Так код будет лучше читаться

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/features/client/ui/СlientSettingsForm/СlientSettingsForm.tsx
> +              loading={isLoading}
Эта реализация не лучше?
https://ant.design/components/form#components-form-demo-validate-only

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/features/group/lib/getOauthLink.ts
> +  url.searchParams.append('v', '5.131');
Вынеси плз в env

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/features/group/model/updateGroup.ts
> +> & { senler_token: string };
Сенлер из группы

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/features/group/ui/GroupSettingsForm/GroupSettingsForm.tsx
> +    console.log(values);
Логи чистить не забывай

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/features/group/ui/GroupSettingsForm/GroupSettingsForm.tsx
> +    if (!group) return;
В таких случаях лучше кидать меседж с ошибкой

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/features/group/ui/GroupSettingsForm/GroupSettingsForm.tsx
> +    form.setFieldsValue({ ['timezone']: group?.timezone, ['city']: group?.city });
Если строка имеет стандартный вид не нужно её оборачивать в [' ... ']

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/features/group/ui/GroupSettingsForm/GroupSettingsForm.tsx
> +                disabled={!!form.getFieldsError().filter(({ errors }) => errors.length).length}
Тут тоже, как в примере выше, лучше использовать реализации из анта

2023-10-23 17:32 UTC, grizzlygarillaz commented on src/widgets/settings/ui/GroupSettingsTab/GroupSettingsTab.tsx
> +  );
Лучше разбить на 2 условия
`if (isFetching)  return ...`
`if (!group?.id) return ...`
`return ...`

2023-10-24 09:48 UTC, KM-DEV01 commented on src/features/group/lib/getOauthLink.ts
> +  url.searchParams.append('v', '5.131');
что именно вынести?

2023-10-24 10:34 UTC, grizzlygarillaz approved these changes

2023-10-24 10:34 UTC, merged