Campaigns settings
MonkeyCodingTeam/huzin-service pull request #14
Opened 2023-11-10 12:41 UTC by KM-DEV01

2023-11-12 13:50 UTC, grizzlygarillaz requested changes
Старайся разбивать ветки, как минимум теги и гостевую страницу можно было делать в разных ветках.
Проверять код легче + проверяется сразу в контексте конкретной задачи.

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/features/campaign/ui/CampaignTemplateTagsUpdate/CampaignTemplateTagsUpdate.tsx
Переделать, слишком много не нужной логики
Код в тупую не копируй

Пример с логикой добавления тега, и то, тоже можно упростить, не обязательно делать "кнопку" для отображения инпута, можно сразу инпут ставить
https://ant.design/components/tag#tag-demo-control

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/features/client/ui/PeriodRadio/PeriodRadio.tsx
> +
Это можно убрать, а колбек использовать в handleChange

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/pages/Target/CampaignsSettingsPage/ui/CampaignsSettingsPage.tsx
> +      {campaignsTemplates ? (
Лучше сделать отображение блока с тегами, даже если их нет, и вывести финформацию о том, что нет тегов и их нужно/можно добавить

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/groupSettings/ui/GroupSettingsTabs/GroupSettingsTabs.tsx
> +export const GroupSettingsTabs = () => {
Почему GroupSettingsTabs?

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/groupSettings/ui/GroupSettingsTabs/GroupSettingsTabs.tsx
> +export const GroupSettingsTabs = () => {
Логика рушится неймингом, вроде таб настройки группы, но содержит в себе настройки клиента и группы, старое название было лучше

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsCampaignsTablesWrapper/GuestStatsCampaignsTablesWrapper.tsx
> +export const GuestStatsCampaignsTablesWrapper: FC<Props> = ({ tableData, isLoading }) => {
Это не врапер. Врапер это обёртка, а что этот компонент оборачивает?

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsTableWrapper/GuestStatsTableWrapper.tsx
Тоже самое - не обёртка

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsTables/GuestStatsTables.tsx
> +    }
monthPeriod и weekPeriod можно заменить на константу в виджете (можно вынести за компнонет, если в этом есть смысл)
`const periodType = {
month: monthPeriod,
week: weekPeriod,
}`

Тогда можно будет использовать periodType[period]. Без свича

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsTables/GuestStatsTables.tsx
> +    setTableDataWithCampaign(groupedData.withCampaign);
А если не будет только "без компаний"?
У тебя "с компаниями" не засетится, в таком случае, логику поправь

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsTables/GuestStatsTables.tsx
> +      <GuestStatsCampaignsTablesWrapper tableData={tableDataWithCampaign} isLoading={isLoading} />
Не получится ли это тоже засунуть в GuestStatsTableWrapper?

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsTablesTitle/GuestStatsTablesTitle.tsx
> +        style={{ marginBottom: marginBottom ? `${marginBottom}` : 0 }}
Если  пропсы опциональные, лучше задавать сразу дефолтные значения
```suggestion
export const GuestStatsTablesTitle: FC<Props> = ({ marginBottom = '0', isLoading = true, title }) => {
  return (
    <Flex justify={'space-between'} align={'center'}>
      <Text
        strong
        className={css.guestTableTitle}
        style={{ marginBottom }}
```

2023-11-12 13:50 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsTablesTitle/GuestStatsTablesTitle.tsx
> +      {isLoading && <Spin />}
Странное использование лоадера

2023-11-13 17:01 UTC, KM-DEV01 commented on src/widgets/guestStats/ui/GuestStatsTables/GuestStatsTables.tsx
> +    }
можно пример?

2023-11-13 17:45 UTC, grizzlygarillaz commented on src/widgets/guestStats/ui/GuestStatsTables/GuestStatsTables.tsx
> +    }
Я ж почти весь код написал

Потом юзать так:
getStats({ ... periodType, id: client.id }, true);

2023-11-13 18:36 UTC, grizzlygarillaz commented
Ты почти все ревью проигнорил

Если что-то не понятно, спрашивай в комментах. У тебя один вопрос и то, где я тебе почти весь код расписал

2023-11-13 19:32 UTC, KM-DEV01 commented on src/features/campaign/ui/CampaignTemplateTagsUpdate/CampaignTemplateTagsUpdate.tsx
убрал логику редактирования тэгов, остальное оставил

2023-11-13 19:42 UTC, KM-DEV01 commented on src/features/client/ui/PeriodRadio/PeriodRadio.tsx
> +
зачем это убирать?

2023-11-13 19:45 UTC, KM-DEV01 commented on src/widgets/groupSettings/ui/GroupSettingsTabs/GroupSettingsTabs.tsx
> +export const GroupSettingsTabs = () => {
произошел overthinking

2023-11-14 08:31 UTC, KM-DEV01 commented on src/widgets/guestStats/ui/GuestStatsTables/GuestStatsTables.tsx
> +    }
умом, спасибо

2023-11-14 09:48 UTC, grizzlygarillaz approved these changes
Пофиксь мелкие недочёты и можно мержить

2023-11-14 09:48 UTC, grizzlygarillaz commented on src/entities/client/model/clientStats.ts
>    date_to: string;
Старайся не дублировать типы такого формата, лучше создать новый тип и уже его использовать

2023-11-14 09:48 UTC, grizzlygarillaz commented on src/features/client/ui/PeriodRadio/PeriodRadio.tsx
> +
Лишняя мемоизация, у тебя и так каждое изменение тригерется он onPeriodChange, только у тебя ещё в памяти хранится массив с депенденси, можно это убрать и дергать евент на onChange

2023-11-14 09:48 UTC, grizzlygarillaz commented on src/widgets/settings/ui/CampaignSettings/CampaignSettings.tsx
> +  if (!isLoading && !campaignTemplate.length) return <EmptyBlock />;
У тебя в этот блок и так попадёт только если isLoading false, можно его убрать

2023-11-14 09:48 UTC, grizzlygarillaz commented on src/widgets/settings/ui/ClientSettingsTabLabel/ClientSettingsTabLabel.tsx
>    return (
У тебя этот компонент никак не привязан к клиенту, это можно вынести просто в настройки, это можно будет потом брать для настроек контента. С табсами тоже самое

2023-11-14 09:48 UTC, grizzlygarillaz commented on src/widgets/settings/ui/ClientSettingsTabs/ClientSettingsTabs.tsx
>    const client = useSelector((state: RootState) => state.selectedClient);
Вот тут уже надо привязать к разделу сервиса (т.е. Таргет), у тебя настройка не только клиента или группа, а и то, и то

2023-11-14 09:51 UTC, grizzlygarillaz commented
И не ресолвь комменты, я потом их в коде найти не могу

2023-11-14 11:53 UTC, KM-DEV01 commented on src/widgets/settings/ui/ClientSettingsTabs/ClientSettingsTabs.tsx
>    const client = useSelector((state: RootState) => state.selectedClient);
опиши, пожалуйста, структуру, которую ты хочешь. 
сейчас это настройки клиента потому что мы настраиваем и **клиента**, и группу **клиента**

2023-11-14 12:07 UTC, grizzlygarillaz commented on src/widgets/settings/ui/ClientSettingsTabs/ClientSettingsTabs.tsx
>    const client = useSelector((state: RootState) => state.selectedClient);
В итоге у тебя останется просто SettingsTab, а SettingsLabel у тебя будет сейчас уже

2023-11-14 12:17 UTC, merged